name: Auto PR to Fork

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          gh pr create --base main --head main --repo yilkalderseh123/sms-price \
            --title "Automated Pull Request from GitHub Actions" \
            --body "This pull request was created automatically using a GitHub Actions workflow."
